import Head from 'next/head';
import Navbar from '../components/Navbar';
import Header from '../components/Header';
import CTA from '../components/CTA';
import Feature from '../components/Features';
import Footer from '../components/Footer';

export default function Home() {
  return (
	<div>
	  <Head>
		<title>My Next.js App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	  </Head>

	  <Navbar />
	  <Header />

	  <main>
		<CTA />
		<div className="container mx-auto mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
		  <Feature title="Feature 1" description="Description for feature 1" />
		  <Feature title="Feature 2" description="Description for feature 2" />
		  <Feature title="Feature 3" description="Description for feature 3" />
		</div>
	  </main>

	  <Footer />
	</div>
  );
}